//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoThuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoThuChi()
        {
            this.ChiTietChis = new HashSet<ChiTietChi>();
            this.ChiTietThus = new HashSet<ChiTietThu>();
        }
    
        public string MaBaoCaoThuChi { get; set; }
        public Nullable<decimal> TongThu { get; set; }
        public Nullable<decimal> TongChi { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<System.DateTime> ThoiGianLap { get; set; }
        public string MaNhanVien { get; set; }
        public string LoaiBaoCao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChi> ChiTietChis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThu> ChiTietThus { get; set; }
    }
}
