//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChi
    {
        public string MaChiTietChi { get; set; }
        public string MaBaoCaoThuChi { get; set; }
        public string MaPhieuNhapHang { get; set; }
    
        public virtual BaoCaoThuChi BaoCaoThuChi { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
